### ISSUE TITLE
Compiler failed at C++ level.  'graphics_copy_texture' is not a member of 'enigma'.  [Game] Error 2

### ISSUE THREAD

**Issue by probe0** [enigma-dev/lgmplugin#59]
Trying to compile sample games now.

 'graphics_copy_texture' is not a member of 'enigma'
 'graphics_copy_texture_part' is not a member of 'enigma'
 'nlpo2dc' is not a member of 'enigma'
mingw32-make.exe: *** [Game] Error 2

When compiling any ENIGMA game: https://pastebin.com/Td0gR6b2
Switching to OpenGL 3.3: https://pastebin.com/kMWVQkk9
Trying to compile a game with a sprite and an object in a room: https://paste.ee/p/UrGdM

**Comment by probe0** [comment]
OpenGL 1.1.

[Run] after [Rebuild all] and disabled all Extensions: https://paste.ee/p/XxFQN -- Same error.

[Run] with [Graphics: None]: https://paste.ee/p/5ZsyW -- Drag & drop error.

Replace Drag & drop [End game] with:
    ///game_end();
    game_end();
Same error but with 'end_game' in 'action_end_game's place.

Removed event--Compile with no graphics: https://paste.ee/p/dC6wi

Compile with Direct3D 9.0: https://paste.ee/p/x3Z6y

**Comment by RobertBColton** [comment]
Can I ask how you ended up with the file "Universal_System/texture_atlas.cpp" when that isn't in that version of the Portable ZIP? We actually fixed these errors recently on our main master branch, a few months ago when we set up continuous integration. Looking in our master branch I do see that `graphics_copy_texture` and everything does exist, because we fixed that. However, the Portable ZIP comes with a version of the engine source from before the texture_atlas was introduced at all. So I'm a little confused at how you happened to have ended up with a version somewhere in the middle.

**Comment by RobertBColton** [comment]
That's great hahaha, I'm glad you got it working. Just a heads up, that Portable ZIP will be going away as our official distribution means for Windows. As I said, there will be more announcements coming soon.
